#!/usr/bin/env bun
/**
 * Generates Caddy configuration for all static file sites.
 * 
 * This script reads all sites from the SQLite database and generates
 * a Caddyfile snippet that can be imported by the main Caddyfile.
 * 
 * Usage: 
 *   bun run scripts/sync-caddy.ts              # Generate config
 *   bun run scripts/sync-caddy.ts --reload     # Generate + reload Caddy
 * 
 * Output: /etc/caddy/sites.d/static-files.caddy (configurable via SF_CADDY_SNIPPET)
 */

import { Database } from "bun:sqlite";
import { mkdirSync, writeFileSync, existsSync, readFileSync } from "fs";
import { dirname } from "path";

// Config
const DB_PATH = process.env.SF_DB_PATH || "/var/lib/kleo-static-files/data/static-files.db";
const CADDY_SNIPPET = process.env.SF_CADDY_SNIPPET || "/etc/caddy/sites.d/static-files.caddy";
const CADDY_CONFIG = process.env.SF_CADDY_CONFIG || "/etc/caddy/Caddyfile";
const CADDY_ADMIN = process.env.CADDY_ADMIN_URL || "http://localhost:2019";
const DOMAIN = process.env.SF_DOMAIN || "498as.com";
const BIND_IPS = process.env.SF_BIND_IPS || "116.203.74.64 2a01:4f8:1c1b:8985::1";

interface Site {
  name: string;
  path: string;
  auth_user: string | null;
  auth_hash: string | null;
}

function generateCaddyConfig(sites: Site[]): string {
  const lines: string[] = [
    "# Auto-generated by kleo-static-files",
    "# Do not edit manually - changes will be overwritten",
    `# Generated: ${new Date().toISOString()}`,
    "",
  ];

  if (sites.length === 0) {
    lines.push("# No sites configured");
    return lines.join("\n");
  }

  for (const site of sites) {
    lines.push(`${site.name}.${DOMAIN} {`);
    lines.push(`    bind ${BIND_IPS}`);
    lines.push("");

    // Basic auth if configured
    if (site.auth_user && site.auth_hash) {
      lines.push("    basic_auth {");
      lines.push(`        ${site.auth_user} ${site.auth_hash}`);
      lines.push("    }");
      lines.push("");
    }

    // File server
    lines.push(`    root * ${site.path}`);
    lines.push("    file_server {");
    lines.push("        index index.html");
    lines.push("    }");
    lines.push("");

    // Logging
    lines.push("    log {");
    lines.push("        output file /var/log/caddy/sites.log {");
    lines.push("            roll_size 10mb");
    lines.push("            roll_keep 5");
    lines.push("        }");
    lines.push("    }");

    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

async function reloadCaddy(): Promise<void> {
  // Use Caddy Admin API to reload config
  // This doesn't require root/systemd access
  try {
    const caddyfile = readFileSync(CADDY_CONFIG, "utf-8");
    
    const response = await fetch(`${CADDY_ADMIN}/load`, {
      method: "POST",
      headers: {
        "Content-Type": "text/caddyfile",
      },
      body: caddyfile,
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Caddy API error: ${error}`);
    }
    
    console.log("Caddy reloaded successfully (via Admin API)");
  } catch (e: any) {
    // If Admin API fails, the config is still written
    // Caddy will pick it up on next restart
    console.log("Note: Could not reload Caddy via API:", e.message);
    console.log("Config written - will apply on Caddy restart");
  }
}

async function main() {
  const shouldReload = process.argv.includes("--reload");
  const dryRun = process.argv.includes("--dry-run");

  // If DB doesn't exist, create empty config (server will create DB on first run)
  if (!existsSync(DB_PATH)) {
    console.log("Database not found, creating empty Caddy config");
    mkdirSync(dirname(CADDY_SNIPPET), { recursive: true });
    writeFileSync(CADDY_SNIPPET, "# No sites yet - database not initialized\n");
    
    if (shouldReload) {
      await reloadCaddy();
    }
    return;
  }

  // Read sites from DB
  const db = new Database(DB_PATH, { readonly: true });
  const sites = db.query<Site, []>(
    "SELECT name, path, auth_user, auth_hash FROM sites"
  ).all();
  db.close();

  console.log(`Found ${sites.length} site(s)`);

  // Generate config
  const config = generateCaddyConfig(sites);

  if (dryRun) {
    console.log("\n--- Generated config (dry run) ---\n");
    console.log(config);
    return;
  }

  // Ensure directory exists
  mkdirSync(dirname(CADDY_SNIPPET), { recursive: true });

  // Write config
  writeFileSync(CADDY_SNIPPET, config);
  console.log(`Written: ${CADDY_SNIPPET}`);

  // Reload Caddy if requested
  if (shouldReload) {
    console.log("Reloading Caddy...");
    await reloadCaddy();
  } else {
    console.log("Run with --reload to apply changes to Caddy");
  }
}

main();
